version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper

  kafka-main:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9000,EXTERNAL://127.0.0.1:9092"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9000,EXTERNAL://0.0.0.0:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_BROKER_ID: 1
    ports:
      - '127.0.0.1:9092:9092'
